title   = "Hugo Theme: hugo-pure"
baseURL = "/"

languageCode   = "en-us"
hasCJKLanguage = true

# [pagination]
# pagerSize = 1

[markup]
[markup.highlight]
noClasses = false
[markup.tableOfContents]
endLevel  = 3

[menus]

[[menus.main]]
identifier = "home"
name       = "Home"
pageRef    = "/"
weight     = 1

[[menus.footer]]
name        = "ðŸ„¯2023"
weight      = 1
[menus.footer.params]
type        = "plain"

[[menus.footer]]
identifier  = "rss"
name        = "Feed"
pageRef     = "/"
weight      = 5
[menus.footer.params]
type        = "link"
format      = "rss"
targetBlank = true

#[params]
#doubleColumns = true

#[outputFormats]
#[outputFormats.myjson]
#baseName  = "myfilename"
#mediaType = "application/json"
#[outputs]
#home = ["html", "rss", "myjson"]

