# default menus

[[main]]
identifier = "home"
name       = "Home"
pageRef    = "/"
weight     = 1

[[footer]]
identifier = "copyright"
pageRef    = "/"
name       = "Â©2023-2024"
weight     = 1

[[footer]]
identifier = "rss"
pageRef    = "/index.xml"
name       = "RSS"
weight     = 3
[[footer.params]]
targetBlank = true
iconClass   = "fa-solid fa-rss"

